workflows:
  android:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        GRADLEW: "./gradlew"
      matrix:
        java_version:
          - adopt@1.11
    scripts:
      - name: Set up Android SDK
        script: |
          yes | sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
      - name: Build with Gradle
        script: |
          $GRADLEW clean
          $GRADLEW assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "lffa.emails@gmail.com"
