workflows:
  android:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        GRADLEW: "./gradlew"
      android:
        components:
          - build-tools;30.0.3
          - platform-tools
          - platforms;android-30
    scripts:
      - name: Build with Gradle
        script: |
          $GRADLEW clean
          $GRADLEW assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "lffa.emails@gmail.com"
