workflows:
  android:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        GRADLEW: "./gradlew"
      android:
        api_level: 30
        build_tools_version: "30.0.3"
      java: "11"
    scripts:
      - name: Build with Gradle
        script: |
          $GRADLEW clean
          $GRADLEW assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "lffa.emails@gmail.com"
