workflows:
  android:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        GRADLEW: "./gradlew"
      java:
        version: "11"
      android:
        components:
          - tools
          - platform-tools
          - build-tools-30.0.3
          - android-30
    scripts:
      - name: Build with Gradle
        script: |
          $GRADLEW clean
          $GRADLEW assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "seuemail@example.com"
