workflows:
  android:
    name: Android build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      vars:
        GRADLEW: "./gradlew"
    scripts:
      - name: Set up Android SDK
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      - name: Set up Java
        script: |
          sdk install java 11.0.11.hs-adpt
          sdk use java 11.0.11.hs-adpt
      - name: Build with Gradle
        script: |
          $GRADLEW clean
          $GRADLEW assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "lffa.emails@gmail.com"
